title: NativeData
description: AOT-first ORM foundation for .NET 10
remote_theme: just-the-docs/just-the-docs@v0.10.0

color_scheme: dark

url: https://skidsh.github.io/NativeData

nav_sort: case_insensitive

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/skidsh/NativeData
  - title: NuGet Packages
    url: https://www.nuget.org/packages?q=NativeData

plugins:
  - jekyll-remote-theme
